### ISSUE TITLE
GameMechanics

### ISSUE THREAD

**Issue by d-frolov** [clockworkrage/epic_mmo_rpg#10]
У вас довольно богатая механика, придираться к второстепенным вещам не буду,
но первое что нужно сделать - разобраться с  бексконечным циклом  
public void run() {
        while (true) {
            stepping();
            TimeHelper.sleep(STEP_TIME);
        }
    }
без возможности корректного выхода.
Вас спасает только System.exit() в админском сервлете. Но это очень грубо. 

лучше оставьте        //server.join();  в Main,
а в гейммеханику этот цикл запускайте отдельным потоком. но c возможностью выхода по interrapted exception. 

Еще мне не нравится для всего кода, что вы "для надежности" все подряд оборачиваете широким try-catch с родительским RuntimeException, и "давите" ошибку простым выводом стектрейса. Получается, что у вас в какой-то момент может получится некорректный стейт, с которым сервер продолжит работу. Хочется какой-то более сложной и корректной логики обработки ошибок.

**Comment by d-frolov** [comment]
На будущее, когда будете изучать потоки. 
1. Надо будет сделать все thread safe.
2. Для userQueue лучше сделать отдельный поток который будет в цикле проверять очередь и создавать бои.
3. ...

**Comment by d-frolov** [comment]
Вы из механики вызываете Repairer.getInstance().repaireUser(userProfile),
который в свою очередь вызывает функцию в самой механике. Зачем?

**Comment by LordNeznay** [comment]
Repairer.getInstance().repaireUser(userProfile) может быть усложнен в будущем. Чтобы при изменении логики ремонта пользователя она поменялась везде, где используется, то логика ремонта вынесена в Repaire.repaireUser.

**Comment by d-frolov** [comment]
Честно - мне не нравится этот подход. Особенно с синглтоном.

**Comment by d-frolov** [comment]
Еще в догонку. Функционал богатый, но получается везде каша из методов которые что-то делают в механике и которые собирают сообщения из строк. Может попробуете как-то сообщения типизировать и спрятать всю работу с JSON внутрь каких-то классов?

**Comment by LordNeznay** [comment]
Попробуем спрятать. Все равно будем переделывать отправку всех сообщений, ибо сейчас они не очень рационально работают относительно трафика и мы это будем оптимизировать.
