### ISSUE TITLE
Отсутствует ресурсная система

### ISSUE THREAD

**Issue by d-frolov** [clockworkrage/epic_mmo_rpg#11]
У вас нет в проекте ресурсной системы. Я понимаю, что может вам удобнее инициализировать карту отдельно и как-то жить с ней, но проект учебный. Пусть будет ресурсная система с одним ресурсом. Пусть не XML а JSON, но это нужно сделать.
Посмотрите примеры к лекциям.

**Comment by LordNeznay** [comment]
https://github.com/clockworkrage/epic_mmo_rpg/commit/fd18014d799eef228eabcbc64f6dc009174f76f8
https://github.com/clockworkrage/epic_mmo_rpg/commit/53bf1fbe0cbc2e288eedd8a2ffdb0473f67028a1
