### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by d-frolov** [clockworkrage/epic_mmo_rpg#12]
1. Не понравилось, как вы вышли из бесконечно цикла. Вакчтически он остался,  но не светится инспекция
2. Я не очень полнял вот эту логику
   public String getResult(){
       if(commandRedPoints > commandBluePoints){
           return getResult(false, "CommandRed");
       } else {
           return getResult(false, "CommandBlue");
       }
   }
   А ничья? И вообще мне странно, что вы возвращаете строковое значение getResult(), которое используете только для верификации.  Ну и тест на это фактически написан дважды
3. config.properties - это не ресурсы, это именно конфиг
4. Создание карты из ресурса не безопасно, может вылететь необрабатываемое исключение.

Итог ревью -4, тесты 5

**Comment by LordNeznay** [comment]
Ну ничьи вроде бы быть не может: либо кто-то набирает нужное количество очков и побеждает, либо кто-то полностью выходит и проигрывает.
