### ISSUE TITLE
подключить jetbrains annotations в pom.xml

### ISSUE THREAD

**Issue by KSolovyev** [clockworkrage/epic_mmo_rpg#17]
у меня не собирается проект. Это плохо. Проект, как только вы его выкачали на новой машине, должен собираться без танцев с бубном. добавьте библитеку и проверьте, что склонированный проект собирается. А так же загляните в инструкцию от jetBrains, что нужно добавлять в репозиторий: https://intellij-support.jetbrains.com/hc/en-us/articles/206827587-How-to-manage-projects-under-Version-Control-Systems

**Comment by KSolovyev** [comment]
!!!

**Comment by LordNeznay** [comment]
У меня не получается воспроизвести проблему. Склонированный проект собирается (чистил перед этим локальный репозиторий).
По поводу инструкции от jetBrains - в начале семестра была дана рекомендация добавить весь каталог .idea в gitignore. К тому же, как я понимаю, он не влияет на запуск проекта и хранит локальные настройки IDE.

**Comment by LordNeznay** [comment]
https://github.com/clockworkrage/epic_mmo_rpg/commit/fabefb16e331f4908152171a6c01ee3cd833d112

**Comment by KSolovyev** [comment]
Если вы подключали библиотеку из папки с идеей, то склонированный проект действительно будет собираться. Но вряд ли эта библиотека будет лежать в той же папке у другого человека.
В папке .idea лежат не только локальные настройки, но так же и периферийные настройки проекта. Инспекции, настройки систем контроля версий, конфигурации запуска, список модулей. Если не подключить их в проект, каждому разработчику прийдется настраивать окружение самостоятельно. Однако сборка с помощью maven'a, и впрадвду, будет работать

**Comment by LordNeznay** [comment]
https://github.com/clockworkrage/epic_mmo_rpg/commit/8eefb89fa1bdd7e8102d639c6ed0444c704524e1
