### ISSUE TITLE
Переопределить в Address метод equals()

### ISSUE THREAD

**Issue by oxeg** [clockworkrage/epic_mmo_rpg#19]
Если переопределяете hashCode(), equals() также нужно переопределять

**Comment by LordNeznay** [comment]
https://github.com/clockworkrage/epic_mmo_rpg/commit/30ceb5f815502d02b3558e64f18c1c7b9f4a5af8

**Comment by oxeg** [comment]
Очень корявенько вы переопределили. У вас на это должна гореть инспекция: https://s.mail.ru/4UiYRDEgR63E/img-2015-12-26-19-48-09.png

**Comment by oxeg** [comment]
Можно воспользоваться идеевским генератором: Code -> Generate (комбинация Alt + Enter). Там можно выбрать equals и hashCode и она сама правильно их переопределит.

**Comment by LordNeznay** [comment]
https://github.com/clockworkrage/epic_mmo_rpg/commit/6c475ed4fbf3f052b1860981616c3209814ad302
