### ISSUE TITLE
Убедиться, что GameMap не будут создаваться бесконечно

### ISSUE THREAD

**Issue by oxeg** [clockworkrage/epic_mmo_rpg#20]
В текущей реализации при бесконечно большом количестве игроков у вас будет бесконечно большое количество потоков GameMap.
Нужно это подпереть.

**Comment by LordNeznay** [comment]
https://github.com/clockworkrage/epic_mmo_rpg/commit/6a2636e67c774370ee233d6cbc7c4d2adb60a355
