### ISSUE TITLE
Подключите аннотации через maven

### ISSUE THREAD

**Issue by d-frolov** [clockworkrage/epic_mmo_rpg#23]
Без этого не собирается

```
    <dependency>
        <groupId>org.jetbrains</groupId>
        <artifactId>annotations</artifactId>
        <version>15.0</version>
    </dependency>
```

**Comment by LordNeznay** [comment]
https://github.com/clockworkrage/epic_mmo_rpg/commit/fabefb16e331f4908152171a6c01ee3cd833d112
Аннотации подключил, но проблему воспроизвести у себя не смог. Я клонировал проект, предварительно очистив локальный репозиторий мавена, все собиралось без проблем - то ли они как-то автоматически внутри идеи подключаются, то ли не знаю, куда копать

**Comment by d-frolov** [comment]
в pom.xml добавь.  Я думаю у тебя локально как-то подключены

**Comment by LordNeznay** [comment]
Добавил (https://github.com/clockworkrage/epic_mmo_rpg/commit/fabefb16e331f4908152171a6c01ee3cd833d112). Скорее всего так и есть, поскольку их пришлось при добавлении выкачать.
