### ISSUE TITLE
TimeHelper

### ISSUE THREAD

**Issue by d-frolov** [clockworkrage/epic_mmo_rpg#24]
Я вот на это код ругаюсь не потому, что printStackTrace(), это как раз и не плохо, а потому, что таким образом давится исключение. Так нельзя.

```
public static void sleep(int period) {
    try {
        Thread.sleep(period);
    } catch (InterruptedException e) {
        //e.printStackTrace();
        return;
    }
}
```

Подсказка. Так как у вас все вызовы sleep() внутри сервлетов, то можно легко их обработать или выбросить наружу

**Comment by LordNeznay** [comment]
https://github.com/clockworkrage/epic_mmo_rpg/commit/af83d56914836103bee5ba2c7626a508e152b403
