### ISSUE TITLE
РК2

### ISSUE THREAD

**Issue by madimp** [clockworkrage/epic_mmo_rpg#6]
у каждой вью должен быть свой this.el
у всех форм должен быть один класс form, а не свои классы у каждой отдельно взятой формы. 
events: {
            "submit form"...
наследование: не в базовой вьюхе искать некоторую функцию, а в наследованной определять show, который вызывает родительский show
# main не должно быть, это корень

обособить одинаковые части view, base.xml, back.xml от меняющихся экранов
var playersHtml = Underscore.template( this.playerTemplate, {players: players}); убить

**Comment by LordNeznay** [comment]
https://github.com/clockworkrage/epic_mmo_rpg/commit/473cd1106b44c3343d92b9cc3d616cad0b8e35c3
https://github.com/clockworkrage/epic_mmo_rpg/commit/9acff34815438c39d535f1cf904e4766d3b66d68
https://github.com/clockworkrage/epic_mmo_rpg/commit/0146a4228cbb90d5455007c931ad3d7da588b89d
https://github.com/clockworkrage/epic_mmo_rpg/commit/7b8279c1aa303040adb9de3558c244d0b0218306
https://github.com/clockworkrage/epic_mmo_rpg/commit/daaba632dbb46d35f7707b46563852ea2c67185f
